changed verifying api with verifying backedn

diff --git a/.github/workflows/cicd_testing.yml b/.github/workflows/cicd_testing.yml
--- a/.github/workflows/cicd_testing.yml
+++ b/.github/workflows/cicd_testing.yml
@@ -104,16 +104,16 @@ jobs:
 
       # 12. Verify backend
       - name: Start backend
-    working-directory: ./backend
-    run: |
-      nohup ../venv/bin/python manage.py runserver 0.0.0.0:8000 > backend.log 2>&1 &
+        working-directory: ./backend
+        run: |
+          nohup ../venv/bin/python manage.py runserver 0.0.0.0:8000 > backend.log 2>&1 &
 
-      sleep 5
+          sleep 5
 
-      if grep -q "Starting development server" backend.log; then
-        echo "Backend started successfully."
-      else
-        echo "Backend failed to start."
-        cat backend.log
-        exit 1
-      fi
+          if grep -q "Starting development server" backend.log; then
+            echo "Backend started successfully."
+          else
+            echo "Backend failed to start."
+            cat backend.log
+            exit 1
+          fi
